### ISSUE TITLE
Task to check healthiness of task-scheduler

### ISSUE THREAD

**Issue by minostro** [zcaudate/cronj#10]
I'm using `cronj` as a substitute of cron for a clojure project.  When using `cron` on other projects I always have a task that run every hour and create some entry log, so I know that `cron` is no broken (sometimes because a bad entry definition).  Is there a way in `cronj` to define a task that have access to the `task-scheduler` without doing the following?:

```clojure
(declare cj)

(defn handler []
  (let [workflows-task (cronj/get-task cj "start-workflows-task")]
    {:running (cronj/running? cj)
     :uptime (cronj/uptime cj)
     :tasks (cronj/get-ids cj)
     :start-workflows-enabled (:enabled workflows-task)
     :start-workflows-schedule (:schedule workflows-task)}))

(def log-cronj-status-task
  {:id "log-cronj-status-task"
   :handler handler
   :schedule "0 0 1 * * * *"
   :opt {}})

(def cj (cronj/cronj :entries [log-cronj-status-task]))
```

Declaring cj in the environment just for the purpose of `handler` can access to it, feels hacky to me, but I cannot see a way around it other than pass the task-scheduler reference as a parameter on the task definition.

**Comment by zcaudate** [comment]
Hey milton!

I've never thought about doing that before. What you are doing... as far as I can tell is the only way to check for now.  You've obviously thought about this issue more than me... so when you say that the previous code seems `hacky`.... How would you like to to write it?

**Comment by minostro** [comment]
Hey Chris,

Sorry for my late response, but I've been out of the office recently.  Is it possible to define `cj` with an partial definition of `entries` and then add it more to it later on?  something like this:

```clojure
(def my-task-1
  {:id "task"
   :handler my-task-1-handler
   :schedule "0 0 1 * * * *"
   :opt {}})

(def cj (cronj/cronj :entries [my-task1]))
....
(def my-task-2
  {:id "task"
   :handler my-task-2-handler
   :schedule "0 0 1 * * * *"
   :opt {}})

(cronj/add-entries cj [my-task2])
```

I quickly checked the documentation and I didn't find an API call like that.

**Comment by zcaudate** [comment]
there's `schedule-task` here: https://github.com/zcaudate/cronj/blob/master/src/cronj/core.clj#L48-L52

**Comment by zcaudate** [comment]
i think this is closable, please reopen if you have any more problems
