### ISSUE TITLE
Update dependencies on hara to squelch warning in Clojure 1.7

### ISSUE THREAD

**Issue by timgilbert** [zcaudate/cronj#12]
Hi, I'm getting a bunch of warnings when I import cronj which seem to be manifestations of this hara issue: zcaudate/hara#5

It would be nice if cronj's dependencies could be updated to use hara 2.1.12 or better, which fixes these warnings.

**Comment by zcaudate** [comment]
not a problem. will do that asap

**Comment by zcaudate** [comment]
Okay, 1.4.4 has been deployed. Let me know if this fixes the problem

**Comment by timgilbert** [comment]
That works great - thanks!
